### ISSUE TITLE
Tagger.yml BUGGED

### ISSUE THREAD

**Issue by n4xo-dev** [Soft-Coders/SIInt#36]
# El Problema
La *GitHub Action* definida por tagger.yml no actualiza las versiones de la forma deseada. Cuando se realiza un merge toma como mensaje **todos los commits** realizados en la rama a la que se hace *pull*. Y de esta forma toma la etiqueta con mayor peso para actualizar la versión (generalemente #minor). 

> Ejemplo del Bug:
![Ejemplo del Bug](https://i.imgur.com/mqCJh2W.png "Ejemplo del Bug")

# Solución
El problema se encontraba en el atributo `fetch-depth: '0'` dentro  de *tagger.yml*. Este atributo se encargaba de obtener  todos los mensajes de todos los commits de la rama involucrada. Al remover este atributo el problema debería de estar completamente resuelto.

> El problema:
![El problema](https://i.imgur.com/Nb6ORDm.png "El problema")

**Comment by iLopezosa** [comment]
La solución ha parecido dar resultado. Se cierra el Issue hasta que se vuelvan a encontrar problemas.

**Comment by n4xo-dev** [comment]
La solución ha parecido dar resultado. Se cierra el Issue hasta que se vuelvan a encontrar problemas.
