### ISSUE TITLE
Transaccion.java - cantidad Integer?

### ISSUE THREAD

**Issue by martame18** [Soft-Coders/SIInt#47]
Ahora mismo la entidad Transaccion tiene el atributo cantidad establecido como un Integer, mas para la realización de CambioDivisa sería necesario cambiarlo a Double. Este cambio supondría algún problema para otra entidad?

**Comment by n4xo-dev** [comment]
@martame18 Este cambio **no afectaría** a ninguna de las entidades del módulo `eburyApp-jpa`. Y, en cuanto a los EJBs, en el que he desarrollado yo **no afectaría** a su funcionamiento en absoluto.
✅

**Comment by ghost** [comment]
@iLopezosa De todas formas, qué necesidad hay de poner Integer en vez de Long?

**Comment by n4xo-dev** [comment]
> @iLopezosa De todas formas, qué necesidad hay de poner Integer en vez de Long?

@pablohud Se está discutiendo cambiar una variable de Integer a Double.
