### ISSUE TITLE
No se puede eliminar la cuenta de la base de datos, solo inutilizarla

### ISSUE THREAD

**Issue by jesuscestino** [Soft-Coders/SIInt#49]
https://github.com/Soft-Coders/SIInt/blob/35b95b98c27914129db4df9550a6af422f2aa84e/source/eburyApp/eburyApp-ejb/src/main/java/es/uma/softcoders/eburyApp/ejb/CuentaEJB.java#L50

> @martame18

**Comment by martame18** [comment]
Arreglado
