### ISSUE TITLE
AltaCliente no debería de comprobar los autorizados de una empresa

### ISSUE THREAD

**Issue by ghost** [Soft-Coders/SIInt#59]
https://github.com/Soft-Coders/SIInt/blob/2198d44579fdf5e5355c21b2c0765d274dc9d321/source/eburyApp/eburyApp-ejb/src/main/java/es/uma/softcoders/eburyApp/ejb/ClienteEJB.java#L58

La relación empresa -> persona autorizada no es obligatoria, no debería de lanzar una excepción si no hay ninguna

**Comment by n4xo-dev** [comment]
Nada que objetar.

**Comment by ghost** [comment]
Arreglado.
