### ISSUE TITLE
Este try no debería de existir (recoge la excepción, por lo que es malo para debuggear)

### ISSUE THREAD

**Issue by ghost** [Soft-Coders/SIInt#60]
https://github.com/Soft-Coders/SIInt/blob/3aaa1187b78796679c6b84f2a5b99af35232a71d/source/eburyApp/eburyApp-ejb/src/main/java/es/uma/softcoders/eburyApp/ejb/TransaccionEJB.java#L64

**Comment by n4xo-dev** [comment]
Al imprimir información del error tampoco **impide** debugging. Pero sería preferible lanzar excepción esperada con mensaje descriptivo.

**Comment by ghost** [comment]
arreglado
