### ISSUE TITLE
No comprendo muy bien esta operación

### ISSUE THREAD

**Issue by ghost** [Soft-Coders/SIInt#61]
https://github.com/Soft-Coders/SIInt/blob/d83a944df9db40a41bac2a4c43256e1df7475db5/source/eburyApp/eburyApp-ejb/src/main/java/es/uma/softcoders/eburyApp/ejb/TransaccionEJB.java#L117

1. la conversión (long) no hace falta, ya que se están operando dos cosas already Long
2. a estas dejándolo como el saldo que le quedaría a la cuenta asociada a esa divisa, por lo que no comprendo muy bien el if situado dos líneas justo debajo

**Comment by n4xo-dev** [comment]
1. Nada que añadir.
2. La comparación correcta podría ser `a < 0` o `corigen.getSaldo() < cant`.

**Comment by ghost** [comment]
Cambiado
