### ISSUE TITLE
Se podría poner Usuario y Contraseña como parámetros de entrada como medida de seguridad

### ISSUE THREAD

**Issue by ghost** [Soft-Coders/SIInt#62]
https://github.com/Soft-Coders/SIInt/blob/510a0a90d196c12513e066b4b043f5c659664781/source/eburyApp/eburyApp-ejb/src/main/java/es/uma/softcoders/eburyApp/ejb/ClienteEJB.java#L116

Es solo una sugerencia, no compromete a la funcionalidad, pero no vendría mal tampoco

**Comment by n4xo-dev** [comment]
Buena sugerencia. Relativamente fácil de aplicar. No priorizar.

**Comment by ghost** [comment]
De momento, para complicar la lógica lo menos posible, intentaremos hacerlo con la capa de presentación, si da problemas lo modificaremos
