### ISSUE TITLE
Cambio a testear en web.xml

### ISSUE THREAD

**Issue by jesuscestino** [Soft-Coders/SIInt#66]
He revisado los archivos "web.xml" de otros proyectos, como AgendaWeb y otros... y en todos al mapear el Servlet usan como url pattern "/*" o  "/ejemplo/*" y nosotros teniamos definido "*.xhtml", seria conveniente ver si ahora funciona el deployment en mi rama y no da Internal server error en WildFly

**Comment by jesuscestino** [comment]
`<servlet-mapping>
		<servlet-name>Faces Servlet</servlet-name>
		<url-pattern>/*</url-pattern>
	</servlet-mapping>`

**Comment by n4xo-dev** [comment]
@jesuscestino haré deploy en mi portátil en clase de SIIInt. Pondré por aquí los resultados
